language: go

go:
  - 1.7.x
  - 1.8.x
  - master

install:
  - go get "github.com/kardianos/govendor"
  - go get github.com/tools/godep
  - godep get "gopkg.in/yaml.v2" 
  - godep save

script:
  - make